name: moldesign
channels:
  - defaults
  - conda-forge
dependencies:
# Core dependencies
  - python==3.11.*
  - jupyterlab
  - ipywidgets
  - pip

# Dependencies from the molecular design app
  - rdkit
  - xtb-python
  - psutil
  - tqdm

# Pip install Parsl and the local functions
  - pip:
      - -e .
      - jupyterlab-spellchecker
      - ase
      - globus-compute-sdk
      - globus-compute-endpoint
      - scikit-learn
