name: moldesign-demo
channels:
  - defaults
  - conda-forge
dependencies:
# Core dependencies
  - python==3.9.*
  - jupyterlab
  - ipywidgets
  - pip

# Dependencies from the molecular design app
  - scikit-learn==0.23.*
  - matplotlib==3.3.3
  - rdkit==2021.09.01
  - py-cpuinfo<6
  - msgpack-python==1.*
  - xtb-python==20.2
  - psutil
  - tqdm

# Pip install Parsl and the local functions
  - pip:
      - -e .
      - jupyterlab-spellchecker
      - ase
